url: https://ahmetsina.github.io
baseurl: /campingklause/

# Site settings
title: Camping Klause - Oberstdorf
email: info@campingklause.com
description: "Herzlich Willkommen in der Camping-Klause, die Gaststätte mit Biergarten in Oberstdorf."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://m.facebook.com/people/Gaststätte-Campingklause/100063707823582/
# Postal address (add as many lines as necessary)
address:
  - line: Camping, Rubinger Str. 16
  - line: 87561 Oberstdorf

# Build settings
markdown: kramdown
permalink: pretty
